//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SeNA80.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "17.1.0.0")]
    public sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("A")]
        public string Am_1_lbl {
            get {
                return ((string)(this["Am_1_lbl"]));
            }
            set {
                this["Am_1_lbl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("a.apr")]
        public string Am_1_prtcl {
            get {
                return ((string)(this["Am_1_prtcl"]));
            }
            set {
                this["Am_1_prtcl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C")]
        public string Am_2_lbl {
            get {
                return ((string)(this["Am_2_lbl"]));
            }
            set {
                this["Am_2_lbl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c.apr")]
        public string Am_2_prtcl {
            get {
                return ((string)(this["Am_2_prtcl"]));
            }
            set {
                this["Am_2_prtcl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("G")]
        public string Am_3_lbl {
            get {
                return ((string)(this["Am_3_lbl"]));
            }
            set {
                this["Am_3_lbl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("g.apr")]
        public string Am_3_prtcl {
            get {
                return ((string)(this["Am_3_prtcl"]));
            }
            set {
                this["Am_3_prtcl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("T")]
        public string Am_4_lbl {
            get {
                return ((string)(this["Am_4_lbl"]));
            }
            set {
                this["Am_4_lbl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("t.apr")]
        public string Am_4_prtcl {
            get {
                return ((string)(this["Am_4_prtcl"]));
            }
            set {
                this["Am_4_prtcl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public string Am_5_lbl {
            get {
                return ((string)(this["Am_5_lbl"]));
            }
            set {
                this["Am_5_lbl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("default.apr")]
        public string Am_5_prtcl {
            get {
                return ((string)(this["Am_5_prtcl"]));
            }
            set {
                this["Am_5_prtcl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_6_lbl {
            get {
                return ((string)(this["Am_6_lbl"]));
            }
            set {
                this["Am_6_lbl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_6_prtcl {
            get {
                return ((string)(this["Am_6_prtcl"]));
            }
            set {
                this["Am_6_prtcl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_7_lbl {
            get {
                return ((string)(this["Am_7_lbl"]));
            }
            set {
                this["Am_7_lbl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_7_prtcl {
            get {
                return ((string)(this["Am_7_prtcl"]));
            }
            set {
                this["Am_7_prtcl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_8_lbl {
            get {
                return ((string)(this["Am_8_lbl"]));
            }
            set {
                this["Am_8_lbl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_8_prtcl {
            get {
                return ((string)(this["Am_8_prtcl"]));
            }
            set {
                this["Am_8_prtcl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_9_lbl {
            get {
                return ((string)(this["Am_9_lbl"]));
            }
            set {
                this["Am_9_lbl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_9_prtcl {
            get {
                return ((string)(this["Am_9_prtcl"]));
            }
            set {
                this["Am_9_prtcl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_10_lbl {
            get {
                return ((string)(this["Am_10_lbl"]));
            }
            set {
                this["Am_10_lbl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_10_prtcl {
            get {
                return ((string)(this["Am_10_prtcl"]));
            }
            set {
                this["Am_10_prtcl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_11_lbl {
            get {
                return ((string)(this["Am_11_lbl"]));
            }
            set {
                this["Am_11_lbl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_11_prtcl {
            get {
                return ((string)(this["Am_11_prtcl"]));
            }
            set {
                this["Am_11_prtcl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_12_lbl {
            get {
                return ((string)(this["Am_12_lbl"]));
            }
            set {
                this["Am_12_lbl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_12_prtcl {
            get {
                return ((string)(this["Am_12_prtcl"]));
            }
            set {
                this["Am_12_prtcl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_13_lbl {
            get {
                return ((string)(this["Am_13_lbl"]));
            }
            set {
                this["Am_13_lbl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_13_prtcl {
            get {
                return ((string)(this["Am_13_prtcl"]));
            }
            set {
                this["Am_13_prtcl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_14_lbl {
            get {
                return ((string)(this["Am_14_lbl"]));
            }
            set {
                this["Am_14_lbl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_14_prtcl {
            get {
                return ((string)(this["Am_14_prtcl"]));
            }
            set {
                this["Am_14_prtcl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_15_lbl {
            get {
                return ((string)(this["Am_15_lbl"]));
            }
            set {
                this["Am_15_lbl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_15_prtcl {
            get {
                return ((string)(this["Am_15_prtcl"]));
            }
            set {
                this["Am_15_prtcl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_16_lbl {
            get {
                return ((string)(this["Am_16_lbl"]));
            }
            set {
                this["Am_16_lbl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_16_prtcl {
            get {
                return ((string)(this["Am_16_prtcl"]));
            }
            set {
                this["Am_16_prtcl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_17_lbl {
            get {
                return ((string)(this["Am_17_lbl"]));
            }
            set {
                this["Am_17_lbl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_17_prtcl {
            get {
                return ((string)(this["Am_17_prtcl"]));
            }
            set {
                this["Am_17_prtcl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_18_lbl {
            get {
                return ((string)(this["Am_18_lbl"]));
            }
            set {
                this["Am_18_lbl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_18_prtcl {
            get {
                return ((string)(this["Am_18_prtcl"]));
            }
            set {
                this["Am_18_prtcl"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Adenosine")]
        public string Am_1_name {
            get {
                return ((string)(this["Am_1_name"]));
            }
            set {
                this["Am_1_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Cytosine")]
        public string Am_2_name {
            get {
                return ((string)(this["Am_2_name"]));
            }
            set {
                this["Am_2_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Guanine")]
        public string Am_3_name {
            get {
                return ((string)(this["Am_3_name"]));
            }
            set {
                this["Am_3_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Thymidine")]
        public string Am_4_name {
            get {
                return ((string)(this["Am_4_name"]));
            }
            set {
                this["Am_4_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Other")]
        public string Am_5_name {
            get {
                return ((string)(this["Am_5_name"]));
            }
            set {
                this["Am_5_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_6_name {
            get {
                return ((string)(this["Am_6_name"]));
            }
            set {
                this["Am_6_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_7_name {
            get {
                return ((string)(this["Am_7_name"]));
            }
            set {
                this["Am_7_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_8_name {
            get {
                return ((string)(this["Am_8_name"]));
            }
            set {
                this["Am_8_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_9_name {
            get {
                return ((string)(this["Am_9_name"]));
            }
            set {
                this["Am_9_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_10_name {
            get {
                return ((string)(this["Am_10_name"]));
            }
            set {
                this["Am_10_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_11_name {
            get {
                return ((string)(this["Am_11_name"]));
            }
            set {
                this["Am_11_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_12_name {
            get {
                return ((string)(this["Am_12_name"]));
            }
            set {
                this["Am_12_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_13_name {
            get {
                return ((string)(this["Am_13_name"]));
            }
            set {
                this["Am_13_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_14_name {
            get {
                return ((string)(this["Am_14_name"]));
            }
            set {
                this["Am_14_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_15_name {
            get {
                return ((string)(this["Am_15_name"]));
            }
            set {
                this["Am_15_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string Am_16_name {
            get {
                return ((string)(this["Am_16_name"]));
            }
            set {
                this["Am_16_name"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Loggin_YN {
            get {
                return ((bool)(this["Loggin_YN"]));
            }
            set {
                this["Loggin_YN"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25000")]
        public int Max_Lines {
            get {
                return ((int)(this["Max_Lines"]));
            }
            set {
                this["Max_Lines"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UV_Trityl_Inst {
            get {
                return ((bool)(this["UV_Trityl_Inst"]));
            }
            set {
                this["UV_Trityl_Inst"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Cond_Trityl_Inst {
            get {
                return ((bool)(this["Cond_Trityl_Inst"]));
            }
            set {
                this["Cond_Trityl_Inst"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Pres_Mon_Inst {
            get {
                return ((bool)(this["Pres_Mon_Inst"]));
            }
            set {
                this["Pres_Mon_Inst"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("20000")]
        public int Max_TritylPts {
            get {
                return ((int)(this["Max_TritylPts"]));
            }
            set {
                this["Max_TritylPts"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public int Report_Trity {
            get {
                return ((int)(this["Report_Trity"]));
            }
            set {
                this["Report_Trity"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UV1On {
            get {
                return ((bool)(this["UV1On"]));
            }
            set {
                this["UV1On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UV2On {
            get {
                return ((bool)(this["UV2On"]));
            }
            set {
                this["UV2On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UV3On {
            get {
                return ((bool)(this["UV3On"]));
            }
            set {
                this["UV3On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UV4On {
            get {
                return ((bool)(this["UV4On"]));
            }
            set {
                this["UV4On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UV5On {
            get {
                return ((bool)(this["UV5On"]));
            }
            set {
                this["UV5On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UV6On {
            get {
                return ((bool)(this["UV6On"]));
            }
            set {
                this["UV6On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UV7On {
            get {
                return ((bool)(this["UV7On"]));
            }
            set {
                this["UV7On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool UV8On {
            get {
                return ((bool)(this["UV8On"]));
            }
            set {
                this["UV8On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Pres1On {
            get {
                return ((bool)(this["Pres1On"]));
            }
            set {
                this["Pres1On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Pres2On {
            get {
                return ((bool)(this["Pres2On"]));
            }
            set {
                this["Pres2On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Pres3On {
            get {
                return ((bool)(this["Pres3On"]));
            }
            set {
                this["Pres3On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Cond1On {
            get {
                return ((bool)(this["Cond1On"]));
            }
            set {
                this["Cond1On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Cond2On {
            get {
                return ((bool)(this["Cond2On"]));
            }
            set {
                this["Cond2On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Cond3On {
            get {
                return ((bool)(this["Cond3On"]));
            }
            set {
                this["Cond3On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Cond4On {
            get {
                return ((bool)(this["Cond4On"]));
            }
            set {
                this["Cond4On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Cond5On {
            get {
                return ((bool)(this["Cond5On"]));
            }
            set {
                this["Cond5On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Cond6On {
            get {
                return ((bool)(this["Cond6On"]));
            }
            set {
                this["Cond6On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Cond7On {
            get {
                return ((bool)(this["Cond7On"]));
            }
            set {
                this["Cond7On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Cond8On {
            get {
                return ((bool)(this["Cond8On"]));
            }
            set {
                this["Cond8On"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool bView_Trityl_Labels {
            get {
                return ((bool)(this["bView_Trityl_Labels"]));
            }
            set {
                this["bView_Trityl_Labels"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.22")]
        public double Threshold {
            get {
                return ((double)(this["Threshold"]));
            }
            set {
                this["Threshold"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int UV_Report {
            get {
                return ((int)(this["UV_Report"]));
            }
            set {
                this["UV_Report"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\SeNA\\")]
        public string Program_Path {
            get {
                return ((string)(this["Program_Path"]));
            }
            set {
                this["Program_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\SeNA\\protocol\\")]
        public string Protocol_Path {
            get {
                return ((string)(this["Protocol_Path"]));
            }
            set {
                this["Protocol_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\SeNA\\sequence\\")]
        public string Sequence_Path {
            get {
                return ((string)(this["Sequence_Path"]));
            }
            set {
                this["Sequence_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\SeNA\\log\\")]
        public string Log_Path {
            get {
                return ((string)(this["Log_Path"]));
            }
            set {
                this["Log_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("C:\\SeNA\\config\\")]
        public string Config_Path {
            get {
                return ((string)(this["Config_Path"]));
            }
            set {
                this["Config_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("300000")]
        public int Log_Interval {
            get {
                return ((int)(this["Log_Interval"]));
            }
            set {
                this["Log_Interval"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("c:\\SeNA\\Trityl\\")]
        public string CSV_Path {
            get {
                return ((string)(this["CSV_Path"]));
            }
            set {
                this["CSV_Path"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("L_01082017.log")]
        public string Cur_Log_File {
            get {
                return ((string)(this["Cur_Log_File"]));
            }
            set {
                this["Cur_Log_File"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("UV_BAR_08071935.CSV")]
        public string UV_Bar_File {
            get {
                return ((string)(this["UV_Bar_File"]));
            }
            set {
                this["UV_Bar_File"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool UniversalSupport {
            get {
                return ((bool)(this["UniversalSupport"]));
            }
            set {
                this["UniversalSupport"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Pol_Freq {
            get {
                return ((int)(this["Pol_Freq"]));
            }
            set {
                this["Pol_Freq"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Rpt_AreaHeight {
            get {
                return ((int)(this["Rpt_AreaHeight"]));
            }
            set {
                this["Rpt_AreaHeight"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Am_Pres_Alarm {
            get {
                return ((bool)(this["Am_Pres_Alarm"]));
            }
            set {
                this["Am_Pres_Alarm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Reg_Pres_Alarm {
            get {
                return ((bool)(this["Reg_Pres_Alarm"]));
            }
            set {
                this["Reg_Pres_Alarm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Trityl_Alarm {
            get {
                return ((bool)(this["Trityl_Alarm"]));
            }
            set {
                this["Trityl_Alarm"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Trityl_Amount {
            get {
                return ((int)(this["Trityl_Amount"]));
            }
            set {
                this["Trityl_Amount"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Reg_Pres_Amt {
            get {
                return ((int)(this["Reg_Pres_Amt"]));
            }
            set {
                this["Reg_Pres_Amt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int Am_Pres_Amt {
            get {
                return ((int)(this["Am_Pres_Amt"]));
            }
            set {
                this["Am_Pres_Amt"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("112")]
        public int DeadVol {
            get {
                return ((int)(this["DeadVol"]));
            }
            set {
                this["DeadVol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int View_VlvStat {
            get {
                return ((int)(this["View_VlvStat"]));
            }
            set {
                this["View_VlvStat"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double AmiditeFC {
            get {
                return ((double)(this["AmiditeFC"]));
            }
            set {
                this["AmiditeFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double ReagentFC {
            get {
                return ((double)(this["ReagentFC"]));
            }
            set {
                this["ReagentFC"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("10.1")]
        public double AmiditePCalib {
            get {
                return ((double)(this["AmiditePCalib"]));
            }
            set {
                this["AmiditePCalib"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("12.1")]
        public double ReagentPCalib {
            get {
                return ((double)(this["ReagentPCalib"]));
            }
            set {
                this["ReagentPCalib"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool QuickLogin {
            get {
                return ((bool)(this["QuickLogin"]));
            }
            set {
                this["QuickLogin"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("25")]
        public string LoginUser {
            get {
                return ((string)(this["LoginUser"]));
            }
            set {
                this["LoginUser"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public string def_Prep_Protocol {
            get {
                return ((string)(this["def_Prep_Protocol"]));
            }
            set {
                this["def_Prep_Protocol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public string def_Run_Protocol {
            get {
                return ((string)(this["def_Run_Protocol"]));
            }
            set {
                this["def_Run_Protocol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("40")]
        public string def_Post_Protocol {
            get {
                return ((string)(this["def_Post_Protocol"]));
            }
            set {
                this["def_Post_Protocol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public int def_Trityl_Label {
            get {
                return ((int)(this["def_Trityl_Label"]));
            }
            set {
                this["def_Trityl_Label"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool Autoscale_Amidites {
            get {
                return ((bool)(this["Autoscale_Amidites"]));
            }
            set {
                this["Autoscale_Amidites"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("3")]
        public double SF_30 {
            get {
                return ((double)(this["SF_30"]));
            }
            set {
                this["SF_30"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.2")]
        public double SF_02 {
            get {
                return ((double)(this["SF_02"]));
            }
            set {
                this["SF_02"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0.5")]
        public double SF_05 {
            get {
                return ((double)(this["SF_05"]));
            }
            set {
                this["SF_05"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("1")]
        public double SF_10 {
            get {
                return ((double)(this["SF_10"]));
            }
            set {
                this["SF_10"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("2")]
        public double SF_20 {
            get {
                return ((double)(this["SF_20"]));
            }
            set {
                this["SF_20"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("5")]
        public double SF_50 {
            get {
                return ((double)(this["SF_50"]));
            }
            set {
                this["SF_50"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int Ltr_12 {
            get {
                return ((int)(this["Ltr_12"]));
            }
            set {
                this["Ltr_12"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4")]
        public double SF_40 {
            get {
                return ((double)(this["SF_40"]));
            }
            set {
                this["SF_40"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string def_Startup_Protocol {
            get {
                return ((string)(this["def_Startup_Protocol"]));
            }
            set {
                this["def_Startup_Protocol"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Tips_Enabled {
            get {
                return ((bool)(this["Tips_Enabled"]));
            }
            set {
                this["Tips_Enabled"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int AmPumpDwell {
            get {
                return ((int)(this["AmPumpDwell"]));
            }
            set {
                this["AmPumpDwell"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("0")]
        public int ReagPumpDwell {
            get {
                return ((int)(this["ReagPumpDwell"]));
            }
            set {
                this["ReagPumpDwell"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Scale_Long {
            get {
                return ((bool)(this["Scale_Long"]));
            }
            set {
                this["Scale_Long"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("True")]
        public bool Double_First {
            get {
                return ((bool)(this["Double_First"]));
            }
            set {
                this["Double_First"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveBar {
            get {
                return ((bool)(this["SaveBar"]));
            }
            set {
                this["SaveBar"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveStrip {
            get {
                return ((bool)(this["SaveStrip"]));
            }
            set {
                this["SaveStrip"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("False")]
        public bool SaveHist {
            get {
                return ((bool)(this["SaveHist"]));
            }
            set {
                this["SaveHist"] = value;
            }
        }
    }
}
